branches:
  only:
  - master
language: scala
scala:
- 2.11.8
sudo: true
env:
  global:
  - DOCKER_PUSH_LATEST=true
  - DOCKER_REPOSITORY=rengahub
  - secure: ayA+gDVZWOOJPUjRp3nNGl+lfC5NGirRvdQXhyLst0pY1v5Yxb0vaeG2BtDWR6di7mkEwUJWvEA3OYTpH3K1W7rqcckMSVYG8GbbqHbDvdUyfBCf35gmhhnG3BhnWAkIQK/itS+ANLOx3mM74T5Nw2ZXavxfXY1nzVfzPi6W9SzZ+KcTwMeGLTO9d/Xa6+1ZQQY4W/sfFdq2l2lizGuP1qbtdJo/HtasWaAYGTdGQvAYzFxqOfgit292edakzFVwyICEznPMZ0i4gaD7TXG247tsl1E162Kfk76viGLfL78nESSfp6HA3X6rj3n1WIhkJSUgGCC58Kf2gqvALrn8RsNb738oMyBBB6yjrLBEFYlUWF/1TImD3+ZKe77G+KzBAQeS4HlcapPOGAouYMEG/oQHXNLSUjyU7RFK8436yDIRbLzk1e3kVIRfoqKvSoIQ4M+S7jXN+ItiJc1sEc1KHca7FqM9S020KgJZwyMJx1mZ2bUuTbv91ORmHwStnigypVJVpd0/Xflu4OxZ0qBktS6oDIBIM/dicOM2nUJFzPKkWvJFZNXlGTHJlogQs2hlwB1RMtqS0+acB0E21lDWP5FZHGmbAd/ogrw0kr4F/Rf40tr//vrGUimDVOn0mD97QOz1cZf3iYpMM71LxRwFkuE4PZCJqMuQu3nBO0HL5BM=
  - secure: nR9tdGNpcdSolARBVcbeaVaoxfjq+O312tEGyyRsTMdMuUxXDnh2IIhgyl/uft8FJRZzjf/VrqFS/1kCDzUOKxR4ch1UWGAu1f5fVks827bDjAjWFfuETAMiGjf6oNZKWIQPZb9mYQX22YaC/KYREURcFaDcqle+bqKR23sNgPQQQ3BPbyVE1K/NYQQ/TyddvqBwm7uBkJFlhmWk8JJVUcwcl7jqafLJqapEQ7QNh6HddjkepkXoUo0vSzvfWZ47AX22rJzFooqImtBLCjiY9u9D9/ztIQXW7mBN7yFStEtoqUVZVltRjpg4+bFKfG3KiEuSNMpO9jjstDzxtvmjmEhByqBxB39GZeaR0jRHXMioLY2z3K/CCzmR/vlGvz/jGmTMf100XHl2Qz9BeAVC8Vc7tbaZpkl/oCyADDqmlUijzw+gtFzeKNIrUiKMH03aZ+tP9dAAdUzjOvoeRzR9kklJIDWXZrIMEilRmOBDmHIS/KxiUVVaxeMpwifAJXsvs6iGaHVWLwyDVJyFZK7sZtzAMYqbQLSgsyuLcic8tsk3+iMm+SXWJ/dwGhg0+OFAH26ISGiQ6kaDUQYZv+iH/C6eLFqM5KwShDr9hWM10k3k6ZRpQF3SX2q1K8ne1dU+tpDiz0VMFzEA6JHirM3VToNS1lmrZ6+kWoKttKeE1qE=
script:
- sbt ++$TRAVIS_SCALA_VERSION test && bash ./.travis/check-code-formatting.sh
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./.travis/deploy-docker.sh
  on:
    branch: master
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
