branches:
  only:
  - master
language: scala
scala:
- '2.11.8'
sudo: true
env: DOCKER_PUSH_LATEST=true
before_script: bash ./.travis/make-nexus-credentials.sh
script:
- sbt ++$TRAVIS_SCALA_VERSION test && bash ./.travis/check-code-formatting.sh
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./.travis/deploy-artifacts.sh
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: bash ./.travis/deploy-docker.sh
  on:
    branch: master

# caching suggestions from http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
