swagger: '2.0'
info:
  description: Renga Project Service.
  title: Renga Project Service
  version: 0.0.1
basePath: /api/projects
tags:
- description: Perform project operations
  name: projects
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: object
            properties:
              projects:
                type: array
                items:
                  $ref: '#/definitions/Project'
        405:
          description: Invalid input
      security:
      - token_auth:
        - projects:read
      summary: List defined projects.
      tags:
      - projects
    post:
      consumes:
      - application/json
      parameters:
      - description: New project to be added.
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/CreateProjectRequest'
      produces:
      - application/json
      responses:
        201:
          description: create successful
          schema:
            $ref: '#/definitions/Project'
        405:
          description: Validation exception
      security:
      - token_auth:
        - projects:write
        - projects:read
      summary: Create a new project.
      tags:
      - projects
  /{project_id}:
    get:
      description: Returns a single project
      parameters:
      - description: ID of project to return
        in: path
        name: project_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Project'
        400:
          description: Invalid ID supplied
        404:
          description: project not found
      security:
      - token_auth:
        - projects:read
      summary: Find project by ID
      tags:
      - projects
securityDefinitions:
  token_auth:
    type: oauth2
    # NOTE the 'authorizationUrl' is automatically added
    flow: implicit
    scopes:
      projects:read: read projects
      projects:write: create and modify projects
definitions:
  CreateProjectRequest:
    type: object
    required:
    - name
    properties:
      labels:
        type: array
        items:
          type: string
      name:
        type: string
    example:
      name: My First Data Science Project
  Project:
    allOf:
    - $ref: '#/definitions/CreateProjectRequest'
    - properties:
        identifier:
          type: string
